### ISSUE TITLE
Inaccuracies in Line count

### ISSUE THREAD

**Issue by aarushi12002** [umang94/word-stats#15]
Eg -`This is line 1. This is another line` 
The above eg has 2 lines but the extension only recognizes 1 line for the lack of a full stop at the end of line 2. 
Looks like the line count works on the splitting based on classic punctuations like ".", "?", "!" which typically end sentences. This is inaccurate given that a clause can be separated by ";" or "," and the words across such punctuations are valid sentences.

**Comment by umang94** [comment]
Take a look at at this [commit](https://github.com/umang94/word-stats/commit/06f4b6b95749fa106fa51a2856e898a9ab540527) for reference.

**Comment by aarushi12002** [comment]
I did after creating this issue.

**Comment by aarushi12002** [comment]
hmm not really an issue, closing this.
